// Generated by gencpp from file prochesta_arm_motion/JointSrv.msg
// DO NOT EDIT!


#ifndef PROCHESTA_ARM_MOTION_MESSAGE_JOINTSRV_H
#define PROCHESTA_ARM_MOTION_MESSAGE_JOINTSRV_H

#include <ros/service_traits.h>


#include <prochesta_arm_motion/JointSrvRequest.h>
#include <prochesta_arm_motion/JointSrvResponse.h>


namespace prochesta_arm_motion
{

struct JointSrv
{

typedef JointSrvRequest Request;
typedef JointSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct JointSrv
} // namespace prochesta_arm_motion


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::prochesta_arm_motion::JointSrv > {
  static const char* value()
  {
    return "d421f3b0a197945d8b29bba5c6341ea9";
  }

  static const char* value(const ::prochesta_arm_motion::JointSrv&) { return value(); }
};

template<>
struct DataType< ::prochesta_arm_motion::JointSrv > {
  static const char* value()
  {
    return "prochesta_arm_motion/JointSrv";
  }

  static const char* value(const ::prochesta_arm_motion::JointSrv&) { return value(); }
};


// service_traits::MD5Sum< ::prochesta_arm_motion::JointSrvRequest> should match
// service_traits::MD5Sum< ::prochesta_arm_motion::JointSrv >
template<>
struct MD5Sum< ::prochesta_arm_motion::JointSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::prochesta_arm_motion::JointSrv >::value();
  }
  static const char* value(const ::prochesta_arm_motion::JointSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::prochesta_arm_motion::JointSrvRequest> should match
// service_traits::DataType< ::prochesta_arm_motion::JointSrv >
template<>
struct DataType< ::prochesta_arm_motion::JointSrvRequest>
{
  static const char* value()
  {
    return DataType< ::prochesta_arm_motion::JointSrv >::value();
  }
  static const char* value(const ::prochesta_arm_motion::JointSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::prochesta_arm_motion::JointSrvResponse> should match
// service_traits::MD5Sum< ::prochesta_arm_motion::JointSrv >
template<>
struct MD5Sum< ::prochesta_arm_motion::JointSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::prochesta_arm_motion::JointSrv >::value();
  }
  static const char* value(const ::prochesta_arm_motion::JointSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::prochesta_arm_motion::JointSrvResponse> should match
// service_traits::DataType< ::prochesta_arm_motion::JointSrv >
template<>
struct DataType< ::prochesta_arm_motion::JointSrvResponse>
{
  static const char* value()
  {
    return DataType< ::prochesta_arm_motion::JointSrv >::value();
  }
  static const char* value(const ::prochesta_arm_motion::JointSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PROCHESTA_ARM_MOTION_MESSAGE_JOINTSRV_H
