// Generated by gencpp from file prochesta_arm_motion/JointSrvRequest.msg
// DO NOT EDIT!


#ifndef PROCHESTA_ARM_MOTION_MESSAGE_JOINTSRVREQUEST_H
#define PROCHESTA_ARM_MOTION_MESSAGE_JOINTSRVREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace prochesta_arm_motion
{
template <class ContainerAllocator>
struct JointSrvRequest_
{
  typedef JointSrvRequest_<ContainerAllocator> Type;

  JointSrvRequest_()
    : req(0.0)  {
    }
  JointSrvRequest_(const ContainerAllocator& _alloc)
    : req(0.0)  {
  (void)_alloc;
    }



   typedef float _req_type;
  _req_type req;





  typedef boost::shared_ptr< ::prochesta_arm_motion::JointSrvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::prochesta_arm_motion::JointSrvRequest_<ContainerAllocator> const> ConstPtr;

}; // struct JointSrvRequest_

typedef ::prochesta_arm_motion::JointSrvRequest_<std::allocator<void> > JointSrvRequest;

typedef boost::shared_ptr< ::prochesta_arm_motion::JointSrvRequest > JointSrvRequestPtr;
typedef boost::shared_ptr< ::prochesta_arm_motion::JointSrvRequest const> JointSrvRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::prochesta_arm_motion::JointSrvRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::prochesta_arm_motion::JointSrvRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::prochesta_arm_motion::JointSrvRequest_<ContainerAllocator1> & lhs, const ::prochesta_arm_motion::JointSrvRequest_<ContainerAllocator2> & rhs)
{
  return lhs.req == rhs.req;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::prochesta_arm_motion::JointSrvRequest_<ContainerAllocator1> & lhs, const ::prochesta_arm_motion::JointSrvRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace prochesta_arm_motion

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::prochesta_arm_motion::JointSrvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::prochesta_arm_motion::JointSrvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::prochesta_arm_motion::JointSrvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::prochesta_arm_motion::JointSrvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::prochesta_arm_motion::JointSrvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::prochesta_arm_motion::JointSrvRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::prochesta_arm_motion::JointSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d9e2e500167ba94696705f008dcefd57";
  }

  static const char* value(const ::prochesta_arm_motion::JointSrvRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd9e2e500167ba946ULL;
  static const uint64_t static_value2 = 0x96705f008dcefd57ULL;
};

template<class ContainerAllocator>
struct DataType< ::prochesta_arm_motion::JointSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "prochesta_arm_motion/JointSrvRequest";
  }

  static const char* value(const ::prochesta_arm_motion::JointSrvRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::prochesta_arm_motion::JointSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 req\n"
;
  }

  static const char* value(const ::prochesta_arm_motion::JointSrvRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::prochesta_arm_motion::JointSrvRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.req);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct JointSrvRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::prochesta_arm_motion::JointSrvRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::prochesta_arm_motion::JointSrvRequest_<ContainerAllocator>& v)
  {
    s << indent << "req: ";
    Printer<float>::stream(s, indent + "  ", v.req);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PROCHESTA_ARM_MOTION_MESSAGE_JOINTSRVREQUEST_H
